[package]
name = "cctr-expr"
description = "This is an internal component crate of cctr"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
regex = "1"
thiserror = "1"
winnow = "0.6"
